#!/bin/bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='darwin'
fi

echo 'install curl'

if [[ $platform == 'darwin' ]]; then
  brew install curl
elif [[ $platform == 'linux' ]]; then
  sudo aptitude install curl
fi

echo 'install oh-my-zsh'
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo 'copy needed files'
cp {.zshrc, .gitconfig} ~/
